In [1]:
import pandas as pd

In [7]:
customers=pd.read_csv(r"C:\Users\ADMIN\Downloads\customers-10000.csv")

In [10]:
first_five= customers.head(5)

In [11]:
first_five.dropna()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/

In [18]:
main= customers[['First Name', 'Last Name']]

In [32]:
one_main=main.head(100)

In [33]:
ok=print(one_main['First Name'].str.startswith('s'))

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: First Name, Length: 100, dtype: bool

In [34]:
print(ok)

None

In [42]:
q=customers['Subscription Date']

In [44]:
updated_q=pd.to_datetime(q)

In [49]:
listed_years=customers['Year']=updated_q.dt.year

In [82]:
customers['updated_year']= listed_years
customers['updated_year']

0       2020
1       2020
2       2022
3       2020
4       2021
        ...
9995    2022
9996    2022
9997    2022
9998    2020
9999    2020
Name: updated_year, Length: 10000, dtype: int32

In [54]:
customers.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Year
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/,2020
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/,2020
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/,2022
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/,2020
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/,2021

In [59]:
email_sorted=customers['Domain'] = customers['Email'].str.split('@').str[1]

In [60]:
print(email_sorted)

0       espinoza-francis.net
1           hall-donovan.com
2         blevins-sexton.com
3                anthony.com
4         rangel-shields.com
                ...
9995              bates.info
9996                wade.com
9997      barnett-dorsey.com
9998     villegas-wilcox.com
9999            martinez.com
Name: Email, Length: 10000, dtype: object

In [61]:
print(customers['Domain'].value_counts())

Domain
hart.com               14
buck.com               10
hanson.com             10
castro.com             10
gross.com              10
                       ..
farley.info             1
gordon-bradley.com      1
ortiz-hendricks.com     1
reid-sutton.com         1
villegas-wilcox.com     1
Name: count, Length: 6270, dtype: int64

In [96]:
customers[(customers['updated_year']=='2020') & (customers['Country']=='Norway')]

Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Phone 2, Email, Subscription Date, Website, Year, Domain, updated_year]
Index: []

In [97]:
customers

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Year,Domain,updated_year
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/,2020,espinoza-francis.net,2020
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/,2020,hall-donovan.com,2020
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/,2022,blevins-sexton.com,2022
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/,2020,anthony.com,2020
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/,2021,rangel-shields.com,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,DD0caa06ebf217c,Meghan,Cline,Richardson LLC,Petersport,Cote d'Ivoire,001-270-136-4738x419,001-349-692-1755x055,nicolasandrade@bates.info,2022-04-27,http://thomas-ramos.com/,2022,bates.info,2022
9996,9997,C1C62ff90D0AfED,Jeremiah,Pena,Hodge-Nixon,Briggsport,Namibia,+1-531-494-7645x4844,001-295-324-5502x5411,tracy68@wade.com,2022-01-17,https://www.campbell.com/,2022,wade.com,2022
9997,9998,2EfAa6Fe435A7DA,Peggy,Key,Vang LLC,West Joyceport,United States Virgin Islands,520.109.2482x26052,+1-602-934-5901x95106,mclaughlinjulia@barnett-dorsey.com,2022-01-13,http://www.george-scott.com/,2022,barnett-dorsey.com,2022
9998,9999,5dB06C3Fab5CCCb,Evan,Humphrey,Gould Ltd,Camachochester,Niger,001-465-242-9979,001-639-955-2116x751,velazquezjessica@villegas-wilcox.com,2020-04-14,https://www.payne.info/,2020,villegas-wilcox.com,2020
9999,10000,9903e8fF4D8Ff0F,Melissa,Montgomery,Burns-Holden,Sparkstown,Tunisia,+1-889-682-9490x65400,423.632.2539x98740,ngallagher@martinez.com,2020-06-27,http://nixon.net/,2020,martinez.com,2020

In [103]:
customers['sorted_phone_no']= customers['Phone 1'].str.replace('.','-',regex=False)

In [104]:
customers.head(50)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,Year,Domain,updated_year,sorted_phone_no
0,1,EB54EF1154C3A78,Heather,Callahan,Mosley-David,Lake Jeffborough,Norway,043-797-5229,915.112.1727,urangel@espinoza-francis.net,2020-08-26,http://www.escobar.org/,2020,espinoza-francis.net,2020,043-797-5229
1,2,10dAcafEBbA5FcA,Kristina,Ferrell,"Horn, Shepard and Watson",Aaronville,Andorra,932-062-1802,(209)172-7124x3651,xreese@hall-donovan.com,2020-04-27,https://tyler-pugh.info/,2020,hall-donovan.com,2020,932-062-1802
2,3,67DAB15Ebe4BE4a,Briana,Andersen,Irwin-Oneal,East Jordan,Nepal,8352752061,(567)135-1918,haleybraun@blevins-sexton.com,2022-03-22,https://www.mack-bell.net/,2022,blevins-sexton.com,2022,8352752061
3,4,6d350C5E5eDB4EE,Patty,Ponce,Richardson Group,East Kristintown,Northern Mariana Islands,302.398.3833,196-189-7767x770,hohailey@anthony.com,2020-07-02,https://delacruz-freeman.org/,2020,anthony.com,2020,302-398-3833
4,5,5820deAdCF23EFe,Kathleen,Mccormick,Carson-Burch,Andresmouth,Macao,001-184-153-9683x1497,552.051.2979x342,alvaradojesse@rangel-shields.com,2021-01-17,https://welch.info/,2021,rangel-shields.com,2021,001-184-153-9683x1497
5,6,E1CDEaC63fDd5aA,Trevor,Lee,Maddox Group,Lake Madelineburgh,Senegal,+1-134-348-0265x9132,+1-313-882-4167,briangriffin@chang.org,2021-08-13,https://www.roberts.com/,2021,chang.org,2021,+1-134-348-0265x9132
6,7,3e1187fCcebC8d2,Mathew,Hoffman,"Bender, Pittman and Kidd",West Ralph,Uzbekistan,842.380.1168,(178)178-5447x32603,bauergerald@morrison.com,2020-04-09,http://www.holt.com/,2020,morrison.com,2020,842-380-1168
7,8,47C5cEE243c9A7b,Glenn,Wiggins,Glenn-Harvey,Ambershire,Falkland Islands (Malvinas),245-207-5608x563,8806867785,changkellie@howell.com,2021-04-02,http://carlson.com/,2021,howell.com,2021,245-207-5608x563
8,9,cacaD68a5e4BF4b,Bruce,Payne,"Arroyo, Cain and Hudson",Barrettview,Zimbabwe,391.313.4649x42910,166.227.5055,mayerjerome@hurst-graham.net,2020-11-26,https://www.glenn-snow.com/,2020,hurst-graham.net,2020,391-313-4649x42910
9,10,436b9c41cfb1fa3,Brendan,Franco,"Schaefer, Blair and Shaffer",New Rickey,Ukraine,001-315-224-3556,254-621-7128x7573,kentryan@stone-oneill.com,2021-06-29,http://ruiz.com/,2021,stone-oneill.com,2021,001-315-224-3556
10,11,9653ca648e2E414,Martin,Hawkins,Lopez Inc,Lake Bobton,Mauritania,001-402-567-1320,732-908-7945,danielbuckley@hatfield.info,2021-05-02,https://www.newman.com/,2021,hatfield.info,2021,001-402-567-1320
11,12,e586A2D67bcdB48,Sara,Shaffer,"Dudley, Coleman and Green",Orrland,Gambia,4229986278,001-028-824-7381x56737,gabrielaleach@rose.net,2021-04-07,https://www.hoffman-rubio.com/,2021,rose.net,2021,4229986278
12,13,c388ECa44FFe37c,Dave,Moran,Harrell-Donovan,South Elizabeth,Sweden,575.006.7250x9748,262-029-1096,cartermallory@chung.com,2020-02-28,https://hinton.info/,2020,chung.com,2020,575-006-7250x9748
13,14,f8dddbf9CD6FF92,Glen,Hammond,"Schaefer, Chung and Lin",Pamelatown,Netherlands,001-887-543-3745x055,001-955-888-1987x09071,lweeks@hooper.org,2022-03-03,https://bush-huynh.org/,2022,hooper.org,2022,001-887-543-3745x055
14,15,86Df56BFCc0a7CA,Catherine,Blackwell,"Mack, Garcia and Schaefer",Lake Seth,Dominican Republic,001-915-961-8896x5744,(310)185-3032x0974,calhounalisha@hardin.net,2021-03-30,https://barker-bishop.info/,2021,hardin.net,2021,001-915-961-8896x5744
15,16,2cfDE68A372cC7A,Larry,Newton,Downs PLC,Mannstad,Belize,(216)514-1412,001-449-365-5864x147,ypayne@gaines.biz,2020-08-09,https://figueroa.com/,2020,gaines.biz,2020,(216)514-1412
16,17,14CBc0BDfbE6FEA,Danny,Archer,"Castro, Haney and Hanna",East Diamond,Cook Islands,8416559700,001-212-234-3412x91164,nwu@brady-chen.com,2021-05-21,http://www.callahan.net/,2021,brady-chen.com,2021,8416559700
17,18,48b3ACBfD6A5cdC,Kim,Griffin,Tyler-Levine,New Gwendolyn,Saint Kitts and Nevis,597.367.9499x5429,506.141.4174x6326,harold11@mullen.org,2021-06-02,http://www.mclaughlin-hubbard.net/,2021,mullen.org,2021,597-367-9499x5429
18,19,dB52fA7Bec665C1,Kristin,Valencia,Liu-Douglas,Martinezstad,French Southern Territories,443-671-1725x7073,6244311825,andrewsanders@marks.com,2021-04-17,http://www.myers.com/,2021,marks.com,2021,443-671-1725x7073
19,20,e99DcfDaDac8a06,Hannah,Ramsey,Hicks-Duran,Port Adrianport,Singapore,(822)795-8754x29384,(769)638-7026x967,amy99@booker.com,2020-12-30,http://www.larsen-floyd.biz/,2020,booker.com,2020,(822)795-8754x29384
20,21,28D7BcC82d076F2,Barry,Meadows,"Weiss, King and Morrison",Wallston,Congo,629.168.7457,001-092-440-6540,basschristian@faulkner.com,2020-01-01,https://chavez.com/,2020,faulkner.com,2020,629-168-7457
21,22,Beb0D2e4BA54a51,Roy,Brock,Becker-Woodard,Port Martha,Zimbabwe,001-102-869-0189x1414,303.040.0780x2768,ldelacruz@spence.com,2021-06-27,https://www.norman.org/,2021,spence.com,2021,001-102-869-0189x1414
22,23,EFe791B6Ce06A1A,Patricia,Pope,Zavala-Garcia,East Johnnystad,Tonga,775.341.8738x21724,(786)324-4817x9051,hayleyritter@price.net,2020-05-19,http://www.moyer.com/,2020,price.net,2020,775-341-8738x21724
23,24,Ebe45ac4Ae5e20C,Alan,Stanton,Munoz and Sons,Lake Isaiahview,Costa Rica,(510)542-0174x853,995.008.2375x973,yhebert@hays-rivera.com,2020-01-23,http://young.com/,2020,hays-rivera.com,2020,(510)542-0174x853
24,25,E31a9699DF2A0eF,Philip,Flynn,Morton Ltd,West Guy,Oman,881-632-0721x11032,(881)992-9151x74921,austinhobbs@briggs.com,2020-09-05,http://huerta-cordova.info/,2020,briggs.com,2020,881-632-0721x11032
25,26,0748BdEFeb4834F,Mackenzie,Williamson,Hart-Klein,New Maxhaven,Saint Helena,+1-605-640-1833x70183,656.931.4990,zramos@haney.org,2020-03-06,http://www.allison-clements.com/,2020,haney.org,2020,+1-605-640-1833x70183
26,27,fEB05baEc5ba41d,Emily,Calderon,Todd-Acosta,Lake Sallyport,Cameroon,038.443.6100,618.908.5890,shelley82@jarvis.com,2021-06-17,http://www.larsen.org/,2021,jarvis.com,2021,038-443-6100
27,28,b9B3B5f1ba40FD3,Roberta,Walton,"Lamb, Little and Frazier",Campbellshire,Tonga,805-974-3346x026,001-324-540-6599x3227,sharigriffin@cameron.com,2020-11-15,https://quinn.biz/,2020,cameron.com,2020,805-974-3346x026
28,29,Fc0Bb9CEbeE57b0,Steve,Mack,Cooper Ltd,Marilyntown,Panama,(079)726-1523,061.039.5513,rpace@huynh.com,2021-03-01,http://www.macdonald-lyons.com/,2021,huynh.com,2021,(079)726-1523
29,30,B5e2c7Cc5b2D5C0,Pedro,Jacobson,Hodge-Potts,Port Dariushaven,Guinea,187.217.1436x5325,075.320.9732,emullins@simpson-christensen.com,2021-09-02,http://www.guerra-armstrong.com/,2021,simpson-christensen.com,2021,187-217-1436x5325
30,31,3D72031D22EB2aC,Daniel,Harper,Gray-Collier,Carolinetown,Micronesia,4779933630,+1-544-607-3630x7852,patricialeach@hernandez.biz,2020-07-06,http://www.barajas-hendrix.com/,2020,hernandez.biz,2020,4779933630
31,32,84d3FaE8D176217,Danny,Mayer,"Serrano, Carr and Hurst",West Bernardbury,Niger,+1-232-090-7002x568,(764)539-0967x909,mindy15@fuentes.org,2020-07-15,http://perkins.com/,2020,fuentes.org,2020,+1-232-090-7002x568
32,33,942FAAB8898c6Fc,Jasmine,Owens,Stafford-Shannon,New Ross,Bosnia and Herzegovina,(685)119-0956,5024074926,jake39@little.com,2022-01-02,https://mckee-hill.net/,2022,little.com,2022,(685)119-0956
33,34,F0EdAbc86aac953,Ashley,Davies,Griffin-Ware,Lake Caitlynville,Bouvet Island (Bouvetoya),754.390.8594x022,188-155-9696x06994,mhudson@hardin.com,2021-03-09,https://www.bray.com/,2021,hardin.com,2021,754-390-8594x022
34,35,2f4976cc8F8Cf7D,Shawn,Cruz,Daniel and Sons,Cardenasport,Svalbard & Jan Mayen Islands,309-608-9907,(615)894-4814x344,nlane@kane-pennington.com,2022-05-03,https://www.tran.net/,2022,kane-pennington.com,2022,309-608-9907
35,36,fDbB79FAB142707,Francis,Hubbard,Barron Group,West Makaylaton,Seychelles,+1-895-654-6918x3859,(182)766-9394x4641,savannah10@simpson.com,2021-03-17,https://www.velazquez-wright.com/,2021,simpson.com,2021,+1-895-654-6918x3859
36,37,E75a5870e952cd6,Richard,Bennett,Fuentes LLC,West Tamara,Cote d'Ivoire,795-520-6262x14294,+1-519-673-2725x0502,cristian16@hill-beard.com,2021-01-12,https://www.frederick.com/,2021,hill-beard.com,2021,795-520-6262x14294
37,38,4C8E6AA7Ced5BAF,Vanessa,Hansen,Watkins-Romero,Kerryburgh,Netherlands,+1-134-667-1175x8813,+1-928-497-1358x88633,jasmineaustin@whitehead.info,2020-01-14,https://www.graves.info/,2020,whitehead.info,2020,+1-134-667-1175x8813
38,39,ec75Fb9C6A0DcF1,Joyce,Foster,Randolph LLC,Nataliestad,Korea,655.928.6486,+1-966-669-6464,samuel97@wyatt.com,2020-10-29,https://www.schmitt.com/,2020,wyatt.com,2020,655-928-6486
39,40,C2378a0b119b425,Marc,Medina,Pearson PLC,New Petershire,Japan,1874666215,237-063-6496x65292,karlgarrett@fischer.biz,2020-03-02,http://www.nicholson.org/,2020,fischer.biz,2020,1874666215
40,41,53D27CbE3b3CAf7,Darren,Santana,Guerra LLC,Meyerbury,French Southern Territories,+1-145-916-2809x14415,440.474.1607,biancahenry@hernandez.org,2021-06-11,http://www.gates.net/,2021,hernandez.org,2021,+1-145-916-2809x14415
41,42,3bcBa3CBB7EF52c,Mario,Moreno,Robles and Sons,Cathyview,United States Minor Outlying Islands,001-044-197-2628x678,001-592-920-6308x2332,marisa13@hickman.com,2022-02-12,https://www.gillespie.biz/,2022,hickman.com,2022,001-044-197-2628x678
42,43,DFcebf7063e11ac,Daniel,Bush,Delacruz-Rosario,West Marthaview,Bouvet Island (Bouvetoya),891.885.1826,309.937.8982x96964,billymorris@lambert-irwin.com,2020-02-13,http://www.zhang.com/,2020,lambert-irwin.com,2020,891-885-1826
43,44,fdd4F120dFFaaBA,Vanessa,Davenport,Barrera Group,South Brandi,Guinea,014.539.1066x2855,001-586-506-1699x536,barry91@howe.info,2020-05-10,https://www.davenport.com/,2020,howe.info,2020,014-539-1066x2855
44,45,FA9584DEE86bBbE,Donald,Terry,Beasley-Perez,Port Rickeyport,Isle of Man,(381)211-7562x9960,905.051.0894x82461,kdavies@owen-humphrey.info,2021-01-04,http://www.grimes-summers.com/,2021,owen-humphrey.info,2021,(381)211-7562x9960
45,46,fF8bc9C72D6c38b,Jill,Esparza,Herrera and Sons,Hendricksfort,Indonesia,001-218-793-7724x2810,253.141.8420,gregghendricks@conner-weiss.info,2020-09-24,http://harris.net/,2020,conner-weiss.info,2020,001-218-793-7724x2810
46,47,6ADbBf35FBb6ebc,Tyler,Richard,Cline Inc,Serranoland,San Marino,(030)748-4061,(518)939-6401,alfredbradford@perry.com,2022-04-17,https://www.delacruz.com/,2022,perry.com,2022,(030)748-4061
47,48,a75eDF85cC17DfB,Sonya,Moore,"Riggs, Pena and Hubbard",New Virginiamouth,Guyana,488.725.7447x7670,001-918-561-3514x2980,ngilmore@bush.net,2021-12-25,https://www.tyler.com/,2021,bush.net,2021,488-725-7447x7670
48,49,E95Ce6e2d241660,Jonathon,Gillespie,Harrell Ltd,West Craig,Sudan,(335)620-5477x4774,353.020.5510,vgilbert@romero.biz,2020-06-23,https://www.long-hickman.com/,2020,romero.biz,2020,(335)620-5477x4774
49,50,3E4Ac207eAE0d2E,Ryan,Lin,Harrell-Frank,West Nicolas,Thailand,284-076-2518x537,6934137441,dgould@graham-winters.com,2021-10-06,https://johns-sharp.com/,2021,graham-winters.com,2021,284-076-2518x537